### ISSUE TITLE
Certified Tester AI Testing (CT-AI)

### ISSUE THREAD

**Issue by Danielsoeller** [psyb0t/ezpyai#21]
Just wondering if you created this because of the weird question in the "Certified Tester AI Testing (CT-AI)" https://www.istqb.org/certifications/artificial-inteligence-tester 
Appendix: Additional Question 3 
https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_CT-AI_Sample-Exam-Questions_v1.1.pdf 
Which of the following options is NOT a framework used to develop AI-based software?
a) scikit-learn
b) CNTK
c) MxNet
d) EZPy-AI
Select ONE option. 
Anwnser is: d Is correct. There is currently no AI development framework with this 
name

Would be awesome, I dislike Questions like that.

**Comment by psyb0t** [comment]
> Just wondering if you created this because of the weird question in the "Certified Tester AI Testing (CT-AI)" https://www.istqb.org/certifications/artificial-inteligence-tester Appendix: Additional Question 3 https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_CT-AI_Sample-Exam-Questions_v1.1.pdf Which of the following options is NOT a framework used to develop AI-based software? a) scikit-learn b) CNTK c) MxNet d) EZPy-AI Select ONE option. Anwnser is: d Is correct. There is currently no AI development framework with this name
> 
> Would be awesome, I dislike Questions like that.

ahaha! nope. i didn't even know about that. i just made it because i needed something that's not bloated to do the stuff that's currently implemented. besides the knowledge gatherer. that i just made for the lulz atm.
thx for the comment xD
